Add auth through Facebook, Twitter, Google plus
Onix-Systems/ios-firebase-chat pull request #6
Opened 2016-12-02 16:13 UTC by onix-dolzhenko

- configured app for social networks
- added service for managing Firebase

2016-12-02 16:34 UTC, nezhyborets reviewed
Ошибки как-то так себе обработаны, а потом ты про это вообще забудешь и так они и останутся не обработанными

2016-12-02 16:34 UTC, nezhyborets commented on OnixFirebaseChat/OnixFirebaseChat/Codebase/Common/AppDelegate.swift
> +    var appInstance: ONXFirebaseChat?
Ну вот опять, это же как бы объект для управления экранами и флоу, почему его не назвать screen manager или как-то так? Так как сейчас, кажется что это God object, что пугает

2016-12-05 15:00 UTC, derpoliuk requested changes

2016-12-05 15:00 UTC, derpoliuk commented on OnixFirebaseChat/OnixFirebaseChat/Codebase/Services/ONXFirebaseService.swift
> +    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any]) -> Bool {
Do we need app parameter in this method?

2016-12-05 15:00 UTC, derpoliuk commented on OnixFirebaseChat/OnixFirebaseChat/Codebase/Services/ONXFirebaseService.swift
> +    func configure(){
In some methods you have no space between closing round bracket and opening curly bracket. Please add space in every occurrence to keep code persistent.

2016-12-05 15:00 UTC, derpoliuk commented on OnixFirebaseChat/OnixFirebaseChat/Codebase/Common/ONXFirebaseChat.swift
> +
We need to figure out better name basing on **what** this class will do.

2016-12-05 15:00 UTC, derpoliuk commented on OnixFirebaseChat/OnixFirebaseChat/Codebase/Services/ONXFirebaseService.swift
> +final class ONXFirebaseService: NSObject {
Again, I think we can come up with better name.

2016-12-05 15:04 UTC, onix-dolzhenko commented on OnixFirebaseChat/OnixFirebaseChat/Codebase/Services/ONXFirebaseService.swift
> +final class ONXFirebaseService: NSObject {
Class name came from: https://habrahabr.ru/post/273455/, regarding to: https://github.com/marinbenc/ReactiveWeatherExample/blob/master/WhatsTheWeatherIn/WeatherAPIService.swift

2016-12-06 08:51 UTC, derpoliuk approved these changes

2016-12-06 08:51 UTC, derpoliuk commented
Let's get it going! Merging...

2016-12-06 08:51 UTC, merged